version: '3.4'

networks:
  elk:
    driver: overlay
    attachable: true
  bridge:
    external:
      name: bridge

configs:
  elasticearch_config:
    file: ./elasticsearch/elasticsearch.yml
  logstash_config:
    file: ./logstash/logstash.yml
  logstash_pipeline_config:
    file: ./logstash/conf.d/logstash.conf
  kibana_config:
    file: ./kibana/kibana.yml

services:
  elasticsearch:
    image: elasticsearch:alpine
    configs:
      - source: elasticearch_config
        target: /etc/elasticsearch/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: logstash:alpine
    configs:
      - source: logstash_config
        target: /etc/logstash/logstash.yml
      - source: logstash_pipeline_config
        target: /etc/logstash/conf.d/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
  kibana:
    image: kibana
    environment:
      - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
      - VIRTUAL_PORT=${KIBANA_VIRTUAL_PORT}
    configs:
      - source: kibana_config
        target: /etc/kibana/kibana.yml
    networks:
      - elk
      - bridge
    depends_on:
      - elasticsearch
