version: '3.4'

networks:
  elk:
    driver: overlay
    attachable: true
  bridge:
    external:
      name: bridge
      
volumes:
  elasticsearch_data:
    driver: local

configs:
  elasticearch_config:
    file: ./elasticsearch/elasticsearch.yml
  logstash_config:
    file: ./logstash/logstash.yml
  logstash_pipeline_config:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/kibana.yml

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    configs:
      - source: elasticearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx1024m"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline_config
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 4560:4560
    networks:
      - elk
      - bridge
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx1024m"
      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    environment:
      - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
      - VIRTUAL_PORT=${KIBANA_VIRTUAL_PORT}
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
      - bridge
    depends_on:
      - elasticsearch

